### ISSUE TITLE
Using 'record' in rcon causes a server crash

### ISSUE THREAD

**Issue by nealp9084** [fstd/teeworlds#88]
I may have found a bug that causes a crash. I reproduced it on my own server a few times, but don't have any other machines to try it out on.

Here is my autoexec.cfg: https://gist.github.com/nealp9084/112f43e016fcddab1e3d
Here is the server log: https://gist.github.com/nealp9084/6193361721f34fc87ad0

All I did was start the server, have 0 people inside, log into the rcon with my admin password, and use `record`. It crashed, as the server log shows.

Apparently, the error is caused by a failed assertion in src/engine/server/server.cpp. I'm not too sure how to fix it atm.

**Comment by fstd** [comment]
timeout
